// Generate a supabase-shaped Database type for xavi by introspecting the live DB
// over DATABASE_URL (no Docker, no CLI login). Tables/Views get accurate columns;
// Enums get accurate unions; Functions are listed by name with permissive
// Args/Returns so every .rpc() call compiles. Output -> xavi database.types.ts.
import postgres from 'postgres';
import { writeFileSync } from 'node:fs';

const OUT = 'C:/Users/Ken/Documents/My Projects/xavi/src/app/core/supabase/database.types.ts';
const sql = postgres(process.env.DATABASE_URL, { prepare: false, connect_timeout: 15 });

function tsType(udt, dataType) {
  if (dataType === 'ARRAY') return tsType(udt.replace(/^_/, ''), null) + '[]';
  switch (udt) {
    case 'bool': return 'boolean';
    case 'int2': case 'int4': case 'int8': case 'float4': case 'float8':
    case 'numeric': case 'money': case 'oid': return 'number';
    case 'json': case 'jsonb': return 'Json';
    case 'text': case 'varchar': case 'bpchar': case 'char': case 'name':
    case 'uuid': case 'date': case 'timestamp': case 'timestamptz': case 'time':
    case 'timetz': case 'interval': case 'bytea': case 'inet': case 'cidr': case 'citext':
      return 'string';
    default: return ENUMS.has(udt) ? `Database["public"]["Enums"]["${udt}"]` : 'unknown';
  }
}

const enumRows = await sql`
  select t.typname, e.enumlabel
  from pg_type t join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' order by t.typname, e.enumsortorder`;
const ENUMS = new Map();
for (const r of enumRows) { if (!ENUMS.has(r.typname)) ENUMS.set(r.typname, []); ENUMS.get(r.typname).push(r.enumlabel); }

const cols = await sql`
  select c.table_name, c.column_name, c.is_nullable, c.column_default,
         c.data_type, c.udt_name, t.table_type
  from information_schema.columns c
  join information_schema.tables t
    on t.table_schema = c.table_schema and t.table_name = c.table_name
  where c.table_schema = 'public'
  order by c.table_name, c.ordinal_position`;

const tables = new Map(), views = new Map();
for (const c of cols) {
  const bucket = c.table_type === 'VIEW' ? views : tables;
  if (!bucket.has(c.table_name)) bucket.set(c.table_name, []);
  bucket.get(c.table_name).push(c);
}

const fns = await sql`
  select distinct p.proname
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f' order by p.proname`;

await sql.end({ timeout: 5 });

const ind = (n) => '  '.repeat(n);
function emitTable(name, columns, withWrites) {
  const nn = (c) => c.is_nullable === 'YES';
  const opt = (c) => nn(c) || c.column_default != null;
  const row = columns.map((c) => `${ind(5)}${c.column_name}: ${tsType(c.udt_name, c.data_type)}${nn(c) ? ' | null' : ''}`).join('\n');
  let out = `${ind(4)}${name}: {\n${ind(4)}  Row: {\n${row}\n${ind(4)}  }\n`;
  if (withWrites) {
    const ins = columns.map((c) => `${ind(5)}${c.column_name}${opt(c) ? '?' : ''}: ${tsType(c.udt_name, c.data_type)}${nn(c) ? ' | null' : ''}`).join('\n');
    const upd = columns.map((c) => `${ind(5)}${c.column_name}?: ${tsType(c.udt_name, c.data_type)}${nn(c) ? ' | null' : ''}`).join('\n');
    out += `${ind(4)}  Insert: {\n${ins}\n${ind(4)}  }\n${ind(4)}  Update: {\n${upd}\n${ind(4)}  }\n`;
  }
  out += `${ind(4)}  Relationships: []\n${ind(4)}}`;
  return out;
}

const tableBlocks = [...tables.entries()].map(([n, c]) => emitTable(n, c, true)).join('\n');
const viewBlocks = views.size ? [...views.entries()].map(([n, c]) => emitTable(n, c, false)).join('\n') : '';
const fnBlocks = fns.map((f) => `${ind(4)}${f.proname}: {\n${ind(5)}Args: Record<string, unknown>\n${ind(5)}Returns: unknown\n${ind(4)}}`).join('\n');
const enumBlocks = [...ENUMS.entries()].map(([n, labels]) => `${ind(4)}${n}: ${labels.map((l) => `"${l}"`).join(' | ')}`).join('\n');

const file = `// AUTO-GENERATED by pentahive-app/scripts/gen-types.mjs (DB introspection of the
// shared project iblrotkczdrztenchnzx). Regenerate with the supabase CLI
// (npm run db:types) once Docker or a Supabase access token is available.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
${tableBlocks}
    }
    Views: {
${viewBlocks}
    }
    Functions: {
${fnBlocks}
    }
    Enums: {
${enumBlocks}
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
`;
writeFileSync(OUT, file);
console.log(`Wrote ${OUT}\n  tables: ${tables.size} | views: ${views.size} | functions: ${fns.length} | enums: ${ENUMS.size}`);
